name: Deploy to Plesk

on:
  push:
    branches:
      - main  # Deploy bei jedem Push in den main-Branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Neueste Version verwenden

    - name: Test SSH Connection
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no zabooz@www.passwordplayground.com 'echo "SSH connection successful"'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3  # Neueste Version verwenden
      with:
        host: www.passwordplayground.com  # Nur Domain oder IP ohne Protokoll
        username: zabooz  # Ihr Plesk-SSH-Benutzername
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Private Schlüssel aus GitHub Secrets
        port: 22  # Standard SSH Port
        script: |
          set -e
          cd /var/www/vhosts/passwordplayground.com/httpdocs/  # Korrekt eingestellter Pfad
          git pull origin main
          # Weitere Befehle, falls nötig, wie npm install oder build
          echo "Deployment completed successfully"
