
name: remote ssh command
on: 
    push:
        branches:
            - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}       # z.B. ssh.passwordplayground.com
        username: ${{ secrets.USERNAME }} # Dein SSH-Benutzername
        password: ${{ secrets.PASSWORD }} # Dein SSH-Passwort
        port: 22                               # SSH-Port
        script: |
          cd /react.passwordplayground.com/httpdocs/
          git pull origin staging
 